name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: ua-connect-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://builds.uaudio.com/apps/UA_Connect/UA_Connect_1_4_7_2324_Win.exe -L --output installer.exe

      - shell: cmd
        run: |
          7z.exe x installer.exe &&^
          cd $PLUGINSDIR &&^
          7z.exe x app-64.7z -o"installation"
        
      - shell: cmd
        run: dir
        
      - shell: cmd
        run: xcopy /H /Y /C "UA Connect.exe.Portable.cmd" "$PLUGINSDIR/installation"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "$PLUGINSDIR/installation"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "$PLUGINSDIR/installation/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
